[versions]
paper-api = "1.21-R0.1-SNAPSHOT"
minecraft = "1.21"
fabric-loom = "1.13.3"
fabric-api = "0.100.7+1.21"
fabric-loader = "0.16.0"
sponge-api = "11.0.0-SNAPSHOT"
minestom-api = "1f34e60ea6"
checker = "0.6.42"

[libraries]
paper-api = { module = "io.papermc.paper:paper-api", version.ref = "paper-api" }
fabric-minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
sponge-api = { module = "org.spongepowered:spongeapi", version.ref = "sponge-api" }
minestom-api = { module = "net.minestom:minestom-snapshots", version.ref = "minestom-api" }

[plugins]
fabric-loom = { id = "fabric-loom", version.ref = "fabric-loom" }
checker = { id = "org.checkerframework", version.ref = "checker" }
